spring.application.name=ai.assistant

server.port=8080

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/ai_assistant
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_aql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.ai.openai.api-key=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
spring.ai.openai.base-url=https://openrouter.ai/api
spring.ai.openai.chat.options.model=z-ai/glm-4.5-air:free

spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.cache.enabled=true

app.jwtSecret=A_SUPER_STRONG_SECRET_KEY_THAT_IS_AT_LEAST_32_BYTES_LONG_FOR_SECURITY_REASONS
app.jwtExpirationMs=604800000

logging.level.org.springframework.security=DEBUG